#!/usr/bin/python3

import signal
import sys
from time import sleep

import os

print("UID:{0} GID:{1} PID:{2} Environment:".format(os.getuid(), os.getgid(), os.getpid()))
for k,v in os.environ.items():
    print(" {0}={1}".format(k,v))

if len(sys.argv) > 1 and sys.argv[1] == 'NOWAIT':
   exit(0)

while True:
    sleep(100)
