#!/usr/bin/python3

import signal
from time import sleep

signal.signal(signal.SIGTERM, lambda signum, frame: print("ignoring SIGTERM"))
signal.signal(signal.SIGHUP, lambda signum, frame: print("ignoring SIGHUP"))
signal.signal(signal.SIGINT, lambda signum, frame: print("ignoring SIGINT"))

while True:
    sleep(100)
