#!/bin/bash

SANDBOX=$PWD

myuid=`id -u`
mygid=`id -g`

# Copy the lamp-apps into this sandbox directory so we can work on it.

if [ ! -d $SANDBOX/lamp-apps ]; then
    docker run -i --rm=true -v /home:/home garywiz/chaperone-lamp --disable --exitkills --log err \
	/bin/bash -c "cp -a /apps $SANDBOX/lamp-apps; chown -R $myuid:$mygid $SANDBOX/lamp-apps"
fi

# Run the lamp image using our local copy of chaperone as well as the lamp-apps directory

docker run -t -i -e "TERM=$TERM" --rm=true -v /home:/home \
    --entrypoint $SANDBOX/chaperone garywiz/chaperone-lamp \
    --create $USER/$myuid \
    --config $SANDBOX/lamp-apps/chaperone.d $* \
     /bin/bash
