#!/bin/bash

SANDBOX=$PWD

docker run -t -i -e "TERM=$TERM" --rm=true -v /home:/home --entrypoint=$SANDBOX/chaperone -e "SANDBOX=$SANDBOX" bst/chapdev \
    --config dev/chaperone/sandbox/test.d $* \
    /bin/bash -i
